---
inherit_from: .rubocop_todo.yml

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - spec/fixtures/**/*
    - vendor/bundle/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: '3.2'

# Disabled
Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 200
